### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by cbuchert** [LiveSafe/gulp-html5-lint#11]
I am working to implement gulp-html5-lint. I am writing on OSX and running Gulp in an Ubuntu 16.04 Vagrant. I am requiring gulp-html5-lint in package.json as a dev depencency like so:

`"gulp-html5-lint": "^1.1.0",`

My implementation code looks like nieh:

```javascript
var html5Lint = require("gulp-html5-lint");

gulp.task("html", function () {
  return gulp.src(myHtmlSrc)
    .pipe(html5Lint());
});
```

When this task runs, Gulp errors out with the following message: 

```
/vagrant/node_modules/gulp-html5-lint/lib/gulp-html5-lint.js:59
                _.forEach(results.messages, function(msg) {
                                 ^

TypeError: Cannot read property 'messages' of undefined
    at htmlLintCallback (/vagrant/node_modules/gulp-html5-lint/lib/gulp-html5-lint.js:59:34)
    at Request._callback (/vagrant/node_modules/html5-lint/html5-lint.js:93:16)
    at Request.self.callback (/vagrant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/vagrant/node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/vagrant/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
```

I can successfully make a `curl` request to https://html5.validator.nu from within the Vagrant guest. Ideas?

**Comment by cbuchert** [comment]
Digging into this a little more, I went ahead and remmed out the lodash forEach loop on line 59 and added in a couple console logs (logging err and results):

``` javascript
console.log(err);
console.log(results);
// _.forEach(results.messages, function(msg) {
//     var errorMsg = msg.type + ': ' + msg.message + '\n' +
//         '    at ' + file.path + ':' + msg.lastLine + ':' + msg.lastColumn;
//
//     errorOutputList.push(errorMsg);
// });
```

Console results were as follows:

```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/vagrant/node_modules/html5-lint/html5-lint.js:91:21)
    at Request.self.callback (/vagrant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/vagrant/node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/vagrant/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
undefined
```

I followed this back to the html5-lint module and inserted `console.log(body)` on line 92 of html-lint.js. When I re-ran the script, nothing was logged. Could there be a change with the html5.validator.nu api or somehow the library isn't waiting for the async request to return? I built another curl request to test a few of the options I was seeing in the html5-lint library and seem to be getting valid data back:

```
$ curl -X POST --header "Content-Type: text/html; charset=utf-8" https://html5.validator.nu/?out=json

{"messages":[{"type":"error","message":"End of file seen without seeing a doctype first. Expected “<!DOCTYPE html>”."},{"type":"error","message":"Element “head” is missing a required instance of child element “title”."}]}
```

**Comment by ankittanna** [comment]
+1 I am getting the same issue.

**Comment by ilchemla** [comment]
Found the issue.
The html5-lint version in the `package.json` should be updated to `0.3.0`

**Comment by ilchemla** [comment]
#12

**Comment by cbuchert** [comment]
@ilchemla Can we push this to NPM? NPM is still pulling the previous commit.
