### ISSUE TITLE
Getting error on lint (TypeError: Cannot read property 'messages' of undefined)

### ISSUE THREAD

**Issue by Sawtaytoes** [LiveSafe/gulp-html5-lint#4]
With this pipe:

``` js
.pipe($.html5Lint())
```

I'm getting this error:

``` js
node_modules\gulp-html5-lint\lib\gulp-html5-lint.js:25
                _.forEach(results.messages, function(msg) {
                                 ^

TypeError: Cannot read property 'messages' of undefined
    at htmlLintCallback (C:\tfs2015\DMX Bordeaux\DEV\DocumatrixHost\node_modules\gulp-html5-lint\lib\gulp-html5-lint.js:25:34)
    at Request._callback (C:\tfs2015\DMX Bordeaux\DEV\DocumatrixHost\node_modules\gulp-html5-lint\node_modules\html5-lint\html5-lint.js:79:7
)
    at self.callback (C:\tfs2015\DMX Bordeaux\DEV\DocumatrixHost\node_modules\gulp-html5-lint\node_modules\html5-lint\node_modules\request\r
equest.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\tfs2015\DMX Bordeaux\DEV\DocumatrixHost\node_modules\gulp-html5-lint\node_modules\html5-lint\node_modules\
request\request.js:867:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)

```

**Comment by mike-spainhower** [comment]
Looks like html5-lint isn't giving us any results.  What are you piping in?  Can you use https://www.npmjs.com/package/gulp-debug to print out what is being piped through?

**Comment by rstoenescu** [comment]
Same issue happens to me too. You can fork https://github.com/rstoenescu/gulp-pipes and "npm test"-it. Look into /test/pipes/html.spec.js.

  1) HTML should be able to lint valid HTML:
     Uncaught TypeError: Cannot read property 'messages' of undefined
      at htmlLintCallback (node_modules/gulp-html5-lint/lib/gulp-html5-lint.js:25:34)
      at Request._callback (node_modules/html5-lint/html5-lint.js:86:14)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1082:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
      at endReadableNT (_stream_readable.js:903:12)

  2) HTML should throw error when linting invalid HTML:
     Uncaught TypeError: Cannot read property 'messages' of undefined
      at htmlLintCallback (node_modules/gulp-html5-lint/lib/gulp-html5-lint.js:25:34)
      at Request._callback (node_modules/html5-lint/html5-lint.js:86:14)
      at Request.self.callback (node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request/request.js:1082:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
      at endReadableNT (_stream_readable.js:903:12)

**Comment by rstoenescu** [comment]
Exactly same code worked for me yesterday. Might be an issue with html5-lint package. You may want to downgrade the html5-lint package version...

**Comment by venelinpetrov** [comment]
Any update on this?

**Comment by rstoenescu** [comment]
Yeah. I figured it out. gulp-html5-lint uses html5-lint which in place relies on http://html5.validator.nu to parse the input. This website was down for a while, resulting in html5-lint HTTP errors which led to the errors above. But now the site's up again. Things should work again.

This bug should be closed.

**Comment by mike-spainhower** [comment]
I'm going to close this for now.  Please reopen if you think this plugin is still at fault. 

Aside: I am happy to accept a PR for checking whether the API is up (though maybe this should be in the upstream anyhow).  See #5

**Comment by Sawtaytoes** [comment]
Haven't checked it, but that's probably the issue I was having as well.

**Comment by rstoenescu** [comment]
Please check the PR. I've made a patch for this.
